version: '3.8' 
networks: 
  custom-net:
    external: true
volumes: 
  prometheus_data: {} 
  grafana_data: {}
  
services: 
  node-exporter: 
    image: prom/node-exporter:v1.6.1 
    container_name: node-exporter
    restart: unless-stopped 
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - custom-net 
  prometheus: 
    image: prom/prometheus:v2.47.1
    container_name: prometheus 
    restart: unless-stopped 
    volumes: 
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yaml' 
      - '--storage.tsdb.path=/prometheus' 
      - '--storage.tsdb.retention.time=50d'
      - '--web.console.libraries=/etc/prometheus/console_libraries' 
      - '--web.console.templates=/etc/prometheus/consoles' 
      - '--web.enable-lifecycle' 
    ports: 
      - 9090:9090 
    networks: 
      - custom-net 
  grafana: 
    image: grafana/grafana:10.1.5 
    user: "1001" 
    container_name: grafana 
    ports: 
      - 3000:3000 
    restart: unless-stopped 
    volumes: 
      - ~/promgrafnode/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
      - ~/promgrafnode/grafana:/var/lib/grafana 
    networks: 
      - custom-net 
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:v0.47.2 
    container_name: cadvisor 
    ports: 
      - 8081:8080 
    networks: 
      - custom-net 
    privileged: true
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    depends_on: 
      - redis 
  redis: 
    image: redis:latest 
    container_name: redis 
    ports: 
      - 6379:6379 
    networks: 
      - custom-net