{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image=~\"fl-server|fl-client-1|fl-client-2\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image=~\"fl-server|fl-client-1|fl-client-2\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image=~\"fl-server|fl-client-1|fl-client-2\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total{image=~\"fl-server|fl-client-1|fl-client-2\"} * 100",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Network Rx (in Bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Network Tx (in Bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Container Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_threads{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Container Network TCP Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_network_tcp_usage_total{image=~\"fl-server|fl-client-1|fl-client-2\"}",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}