# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'
#   # - "first.rules"
#   # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# global:
#   scrape_interval:     15s # By default, scrape targets every 15 seconds.

#   # Attach these labels to any time series or alerts when communicating with
#   # external systems (federation, remote storage, Alertmanager).
#   external_labels:
#     monitor: 'codelab-monitor'


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  
  # Monitoring the Docker Engine
  - job_name: 'dockers'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'cadvisor'
    scrape_interval: 15s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 15s
  
    static_configs:
      - targets: ['node-exporter:9100']